// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;

#pragma warning disable 219, 612, 618
#nullable disable

namespace Sundy.Core.CompiledModels
{
    public partial class SundyDbContextModel
    {
        private SundyDbContextModel()
            : base(skipDetectChanges: false, modelId: new Guid("e42d802f-7caa-41dc-8697-d348e6f45a54"), entityTypeCount: 2)
        {
        }

        partial void Initialize()
        {
            var calendar = CalendarEntityType.Create(this);
            var calendarEvent = CalendarEventEntityType.Create(this);

            CalendarEventEntityType.CreateForeignKey1(calendarEvent, calendar);

            CalendarEntityType.CreateAnnotations(calendar);
            CalendarEventEntityType.CreateAnnotations(calendarEvent);

            AddAnnotation("ProductVersion", "10.0.1");
        }
    }
}
