// <auto-generated />
using Microsoft.EntityFrameworkCore.Infrastructure;
using Sundy.Core;
using Sundy.Core.CompiledModels;

#pragma warning disable 219, 612, 618
#nullable disable

[assembly: DbContextModel(typeof(SundyDbContext), typeof(SundyDbContextModel))]
